import { Routes } from '@angular/router';

export const MASTERS_ROUTES: Routes = [
    { path: 'geography/countries', loadChildren: () => import('@features/masters/geography/countries/countries.routes').then((m) => m.COUNTRY_ROUTES) },
    { path: 'geography/regions', loadChildren: () => import('@features/masters/geography/regions/regions.routes').then((m) => m.REGION_ROUTES) },
    { path: 'geography/states', loadChildren: () => import('@features/masters/geography/states/states.routes').then((m) => m.STATE_ROUTES) },
    { path: 'geography/cities', loadChildren: () => import('@features/masters/geography/cities/cities.routes').then((m) => m.CITY_ROUTES) },
    { path: 'geography/airports', loadChildren: () => import('@features/masters/geography/airports/airports.routes').then((m) => m.AIRPORT_ROUTES) },
    { path: 'geography/timezones', loadChildren: () => import('@features/masters/geography/timezones/timezones.routes').then((m) => m.TIMEZONE_ROUTES) },
    { path: 'geography/timezone-dls', loadChildren: () => import('@features/masters/geography/timezone-dls/timezone-dls.routes').then((m) => m.TIMEZONE_DLS_ROUTES) },
    { path: 'airlines/airline-carriers', loadChildren: () => import('@features/masters/airlines/airline-carriers/airline-carriers.routes').then((m) => m.AIRLINECARRIER_ROUTES) },
    { path: 'airlines/airline-aliases', loadChildren: () => import('@features/masters/airlines/airline-aliases/airline-aliases.routes').then((m) => m.AIRLINEALIAS_ROUTES) },
    { path: 'airlines/airline-contacts', loadChildren: () => import('@features/masters/airlines/airline-contacts/airline-contacts.routes').then((m) => m.AIRLINECONTACT_ROUTES) },
    { path: 'airlines/airline-business-roles', loadChildren: () => import('@features/masters/airlines/airline-business-roles/airline-business-roles.routes').then((m) => m.AIRLINEBUSINESSROLE_ROUTES) },
    { path: 'airlines/alliances', loadChildren: () => import('@features/masters/airlines/alliances/alliances.routes').then((m) => m.ALLIANCE_ROUTES) },
    { path: 'airlines/alliance-members', loadChildren: () => import('@features/masters/airlines/alliance-members/alliance-members.routes').then((m) => m.ALLIANCEMEMBER_ROUTES) },
    { path: 'aircraft/aircraft-types', loadChildren: () => import('@features/masters/aircraft/aircraft-types/aircraft-types.routes').then((m) => m.AIRCRAFTTYPE_ROUTES) },
    { path: 'aircraft/aircraft-families', loadChildren: () => import('@features/masters/aircraft/aircraft-families/aircraft-families.routes').then((m) => m.AIRCRAFTFAMILY_ROUTES) },
    { path: 'aircraft/manufacturers', loadChildren: () => import('@features/masters/aircraft/manufacturers/manufacturers.routes').then((m) => m.AIRCRAFTMANUFACTURER_ROUTES) },
    { path: 'aircraft/configurations', loadChildren: () => import('@features/masters/aircraft/configurations/configurations.routes').then((m) => m.AIRCRAFTCONFIGURATION_ROUTES) },
    { path: 'aircraft/configuration-revisions', loadChildren: () => import('@features/masters/aircraft/configuration-revisions/configuration-revisions.routes').then((m) => m.AIRCRAFTCONFIGURATIONREVISION_ROUTES) },
    { path: 'aircraft/cabin-layouts', loadChildren: () => import('@features/masters/aircraft/cabin-layouts/cabin-layouts.routes').then((m) => m.AIRCRAFTCABINLAYOUT_ROUTES) },
    { path: 'aircraft/owners', loadChildren: () => import('@features/masters/aircraft/owners/owners.routes').then((m) => m.AIRCRAFTOWNER_ROUTES) },
    { path: 'aircraft/registrations', loadChildren: () => import('@features/masters/aircraft/registrations/registrations.routes').then((m) => m.AIRCRAFTREGISTRATION_ROUTES) },
    { path: 'flight/service-types', loadChildren: () => import('@features/masters/flight/service-types/service-types.routes').then((m) => m.FLIGHTSERVICETYPE_ROUTES) },
    { path: 'flight/operational-suffixes', loadChildren: () => import('@features/masters/flight/operational-suffixes/operational-suffixes.routes').then((m) => m.OPERATIONALSUFFIX_ROUTES) },
    { path: 'flight/flight-frequencies', loadChildren: () => import('@features/masters/flight/flight-frequencies/flight-frequencies.routes').then((m) => m.FLIGHTFREQUENCY_ROUTES) },
    { path: 'flight/flight-suffixes', loadChildren: () => import('@features/masters/flight/flight-suffixes/flight-suffixes.routes').then((m) => m.FLIGHTSUFFIX_ROUTES) },
    { path: 'flight/traffic-restrictions', loadChildren: () => import('@features/masters/flight/traffic-restrictions/traffic-restrictions.routes').then((m) => m.TRAFFICRESTRICTION_ROUTES) },
    { path: 'flight/traffic-restriction-qualifiers', loadChildren: () => import('@features/masters/flight/traffic-restriction-qualifiers/traffic-restriction-qualifiers.routes').then((m) => m.TRAFFICRESTRICTIONQUALIFIER_ROUTES) },
    { path: 'flight/secure-flight-indicators', loadChildren: () => import('@features/masters/flight/secure-flight-indicators/secure-flight-indicators.routes').then((m) => m.SECUREFLIGHTINDICATOR_ROUTES) },
    { path: 'flight/meal-services', loadChildren: () => import('@features/masters/flight/meal-services/meal-services.routes').then((m) => m.MEALSERVICE_ROUTES) },
    { path: 'flight/electronic-ticket-indicators', loadChildren: () => import('@features/masters/flight/electronic-ticket-indicators/electronic-ticket-indicators.routes').then((m) => m.ELECTRONICTICKETINDICATOR_ROUTES) },
    { path: 'flight/reservation-booking-designators', loadChildren: () => import('@features/masters/flight/reservation-booking-designators/reservation-booking-designators.routes').then((m) => m.RESERVATIONBOOKINGDESIGNATOR_ROUTES) },
    { path: 'flight/reservation-booking-modifiers', loadChildren: () => import('@features/masters/flight/reservation-booking-modifiers/reservation-booking-modifiers.routes').then((m) => m.RESERVATIONBOOKINGMODIFIER_ROUTES) },
    { path: 'schedule/schedule-sources', loadChildren: () => import('@features/masters/schedule/schedule-sources/schedule-sources.routes').then((m) => m.SCHEDULESOURCE_ROUTES) },
    { path: 'schedule/schedule-channels', loadChildren: () => import('@features/masters/schedule/schedule-channels/schedule-channels.routes').then((m) => m.SCHEDULECHANNEL_ROUTES) },
    { path: 'schedule/schedule-statuses', loadChildren: () => import('@features/masters/schedule/schedule-statuses/schedule-statuses.routes').then((m) => m.SCHEDULESTATUS_ROUTES) },
    { path: 'schedule/schedule-types', loadChildren: () => import('@features/masters/schedule/schedule-types/schedule-types.routes').then((m) => m.SCHEDULETYPE_ROUTES) },
    { path: 'schedule/schedule-priorities', loadChildren: () => import('@features/masters/schedule/schedule-priorities/schedule-priorities.routes').then((m) => m.SCHEDULEPRIORITY_ROUTES) },
    { path: 'schedule/schedule-categories', loadChildren: () => import('@features/masters/schedule/schedule-categories/schedule-categories.routes').then((m) => m.SCHEDULECATEGORY_ROUTES) },
    { path: 'schedule/seasons', loadChildren: () => import('@features/masters/schedule/seasons/seasons.routes').then((m) => m.SEASON_ROUTES) },
    { path: 'messaging/action-identifiers', loadChildren: () => import('@features/masters/messaging/action-identifiers/action-identifiers.routes').then((m) => m.ACTIONIDENTIFIER_ROUTES) },
    { path: 'messaging/action-codes', loadChildren: () => import('@features/masters/messaging/action-codes/action-codes.routes').then((m) => m.ACTIONCODE_ROUTES) },
    { path: 'messaging/dei-registry', loadChildren: () => import('@features/masters/messaging/dei-registry/dei-registry.routes').then((m) => m.DEIREGISTRY_ROUTES) },
    { path: 'messaging/data-element-identifiers', loadChildren: () => import('@features/masters/messaging/data-element-identifiers/data-element-identifiers.routes').then((m) => m.DATAELEMENTIDENTIFIER_ROUTES) },
    { path: 'messaging/reject-reasons', loadChildren: () => import('@features/masters/messaging/reject-reasons/reject-reasons.routes').then((m) => m.REJECTREASON_ROUTES) },
    { path: 'messaging/distribution-channels', loadChildren: () => import('@features/masters/messaging/distribution-channels/distribution-channels.routes').then((m) => m.DISTRIBUTIONCHANNEL_ROUTES) },
    { path: 'messaging/message-priorities', loadChildren: () => import('@features/masters/messaging/message-priorities/message-priorities.routes').then((m) => m.MESSAGEPRIORITY_ROUTES) },
    { path: 'messaging/message-statuses', loadChildren: () => import('@features/masters/messaging/message-statuses/message-statuses.routes').then((m) => m.MESSAGESTATUS_ROUTES) },
    { path: 'messaging/standard-message-identifiers', loadChildren: () => import('@features/masters/messaging/standard-message-identifiers/standard-message-identifiers.routes').then((m) => m.STANDARDMESSAGEIDENTIFIER_ROUTES) },
    { path: 'terminal/airport-terminals', loadChildren: () => import('@features/masters/terminal/airport-terminals/airport-terminals.routes').then((m) => m.AIRPORTTERMINAL_ROUTES) },
    { path: 'terminal/passenger-terminals', loadChildren: () => import('@features/masters/terminal/passenger-terminals/passenger-terminals.routes').then((m) => m.PASSENGERTERMINAL_ROUTES) },
    { path: 'terminal/traffic-conference-areas', loadChildren: () => import('@features/masters/terminal/traffic-conference-areas/traffic-conference-areas.routes').then((m) => m.TRAFFICCONFERENCEAREA_ROUTES) },
];

