package com.codeshare.airline.core.dto.aircraft;

import com.codeshare.airline.core.enums.common.Status;
import lombok.*;

import java.time.LocalDate;
import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AircraftConfigurationDTO {

    private UUID id;

    private UUID aircraftTypeId;
    private UUID airlineId;

    private String configurationCode;
    private Boolean autoGenerated;

    private Integer totalSeats;

    private Status statusCode;

    private LocalDate effectiveFrom;
    private LocalDate effectiveTo;
}