spring:
  application:
    name: auth-identity-service
  config:
    import:
      - common-properties-dev.yml
      - common-db-dev.yml
server:
  port: 8081
  servlet:
    context-path: /api/auth
jwt:
  secret: MySuperSecretKey12345678901234567890
  access-expiration: 86400000
  refresh-expiration: 172800000
