spring:
  cloud:
    consul:
      host: localhost
      port: 8500

      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
