logging:
  level:
    com:
      codeshare:
        airline: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  tracing:
    sampling:
      probability: 1

spring:
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true
        register: true
      host: localhost
      port: 8500
