spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
    password: root
    url: jdbc:mysql://localhost:3306/csm
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

#  redis:
#    host: localhost
#    port: 6379
#    timeout: 2000
management:
  health:
    redis:
      enabled: false
