spring:
  application:
    name: gateway-service

  config:
    import:
      - common-properties-dev.yml
      - common-db-dev.yml

  cloud:
    consul:
      discovery:
        watch:
          enabled: false

    gateway:
      server:
        routes:
          - id: auth-identity-service
            uri: lb://auth-identity-service
            predicates:
              - Path=/auth/**
          - id: tenant-service
            uri: lb://tenant-service
            predicates:
              - Path=/tenant/**

        webflux:
          filter:
            weight:
              enabled: false

server:
  port: 8080


swagger:
  services:
    - name: AUTH AND IDENTITY SERVICE
      serviceId: auth-identity-service
      docsPath: /v3/api-docs
      paths:
        - auth
        - users

    - name: TENANT SERVICE
      serviceId: tenant-service
      docsPath: /v3/api-docs
      paths:
        - tenant

springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: AUTH SERVICE
        url: /auth/v3/api-docs
      - name: TENANT SERVICE
        url: /tenant/v3/api-docs
