spring:
  application:
    name: gateway-service

  config:
    import:
      - common-properties-dev.yml
      - common-db-dev.yml

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Transaction-Id, #{T(java.util.UUID).randomUUID()}
        - AddRequestHeader=X-Request-Start-Time, #{T(java.lang.System).currentTimeMillis()}

      routes:

        # AUTH SERVICE
        - id: auth-identity-service
          uri: lb://auth-identity-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - RewritePath=/(?<segment>.*),/api/auth/${segment}

        # TENANT SERVICE
        - id: tenant-service
          uri: lb://tenant-service
          predicates:
            - Path=/tenant/**
          filters:
            - StripPrefix=1
            - RewritePath=/(?<segment>.*),/api/tenant/${segment}

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

server:
  port: 8080

swagger:
  services:
    - name: AUTH AND IDENTITY SERVICE
      serviceId: auth-identity-service
      docsPath: /v3/api-docs
      paths:
        - auth
        - users

    - name: TENANT SERVICE
      serviceId: tenant-service
      docsPath: /v3/api-docs
      paths:
        - tenant

springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: AUTH SERVICE
        url: /auth/v3/api-docs
      - name: TENANT SERVICE
        url: /tenant/v3/api-docs
