spring:
  application:
    name: gateway-service
  config:
    import:
      - classpath:/configurations/${spring.profiles.active}/common-properties.yml
      - classpath:/configurations/${spring.profiles.active}/common-db.yml
      - classpath:/configurations/${spring.profiles.active}/common-env.yml
    gateway:
      routes:
        - id: auth-identity-service
          uri: lb://auth-identity-service
          predicates:
            - Path=/auth/**
        - id: tenant-service
          uri: lb://tenant-service
          predicates:
            - Path=/tenant/**
server:
  port: 8081
swagger:
  services:
    - name: AUTH AND IDENTITY SERVICE
      serviceId: auth-identity-service
      docsPath: /v3/api-docs
      paths:
        - auth
        - users
    - name: TENANT SERVICE
      serviceId: tenant-service
      docsPath: /v3/api-docs
      paths:
        - tenant
springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: AUTH SERVICE
        url: /auth/v3/api-docs
      - name: TENANT SERVICE
        url: /tenant/v3/api-docs
