spring:
  application:
    name: tenant-service
  config:
    import:
      - classpath:/configurations/dev/common-properties.yml
      - classpath:/configurations/dev/common-db.yml
server:
  port: 8082
  servlet:
    context-path: /api/tenant
