spring:
  application:
    name: tenant-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true

server:
  port: 8103
  servlet:
    context-path: /api/tenant

# tenant-specific properties
app:
  tenant:
    default-schema: public

management:
  endpoints:
    web:
      exposure:
        include: health,info
