spring:
  application:
    name: tenant-service

  config:
    import:
      - common-properties-dev.yml
      - common-db-dev.yml
  cloud:
    consul:
      discovery:
        health-check-path: /api/tenant/actuator/health

server:
  port: 8082
  servlet:
    context-path: /api/tenant
