package com.codeshare.airline.data.aircraft.eitities;

import com.codeshare.airline.core.enums.common.Status;
import com.codeshare.airline.data.core.eitities.AirlineCarrier;
import com.codeshare.airline.persistence.persistence.entity.CSMDataAbstractEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

@Entity
@Table(
        name = "MASTER_AIRCRAFT_CONFIGURATION",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "UK_CONFIG_CODE_AIRLINE",
                        columnNames = {"CONFIGURATION_CODE", "AIRLINE_ID"}
                )
        },
        indexes = {
                @Index(name = "IDX_CONFIG_TYPE", columnList = "AIRCRAFT_TYPE_ID"),
                @Index(name = "IDX_CONFIG_AIRLINE", columnList = "AIRLINE_ID"),
                @Index(name = "IDX_CONFIG_STATUS", columnList = "STATUS_CODE")
        }
)
@Getter
@Setter
@NoArgsConstructor
public class AircraftConfiguration extends CSMDataAbstractEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "AIRCRAFT_TYPE_ID",
            nullable = false,
            foreignKey = @ForeignKey(name = "FK_CONFIG_AIRCRAFT_TYPE")
    )
    private AircraftType aircraftType;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "AIRLINE_ID",
            nullable = false,
            foreignKey = @ForeignKey(name = "FK_CONFIG_AIRLINE")
    )
    private AirlineCarrier airline;

    @Column(name = "CONFIGURATION_CODE", nullable = false, length = 50)
    private String configurationCode;

    @Column(name = "AUTO_GENERATED", nullable = false)
    private Boolean autoGenerated = Boolean.FALSE;

    @Column(name = "TOTAL_SEATS", nullable = false)
    private Integer totalSeats;

    @Enumerated(EnumType.STRING)
    @Column(name = "STATUS", nullable = false, length = 20)
    private Status status;

    @Column(name = "description")
    private String description;

    @Column(name = "EFFECTIVE_FROM")
    private LocalDate effectiveFrom;

    @Column(name = "EFFECTIVE_TO")
    private LocalDate effectiveTo;


    @PrePersist
    @PreUpdate
    private void normalizeAndValidate() {

        if (configurationCode != null) {
            configurationCode = configurationCode.trim().toUpperCase();
        }

        if (totalSeats == null || totalSeats <= 0) {
            throw new IllegalStateException("Total seats must be greater than zero.");
        }

        if (effectiveFrom != null && effectiveTo != null &&
                effectiveFrom.isAfter(effectiveTo)) {
            throw new IllegalStateException("Invalid effective period.");
        }
    }
}
