package com.codeshare.airline.platform.core.dto.master.aircraft;

import com.codeshare.airline.platform.core.enums.common.RecordStatus;
import lombok.*;

import java.time.LocalDate;
import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AircraftConfigurationDTO {

    private UUID id;

    private UUID aircraftTypeId;
    private UUID airlineId;

    private String configurationCode;
    private String configurationName;
    private Boolean autoGenerated;

    private Integer totalSeats;

    private Boolean active;
    private RecordStatus recordStatus;

    private LocalDate effectiveFrom;
    private LocalDate effectiveTo;
}
