spring:
  application:
    name: gateway-service

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_IDENTITY_ISSUER_URI:http://localhost:8081}

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**

        - id: schedule-service
          uri: ${SCHEDULE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/schedule/**

        - id: codeshare-service
          uri: ${CODESHARE_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/codeshare/**

server:
  port: ${GATEWAY_SERVICE_PORT:8080}

management:
  endpoints:
    web:
      base-path: ${ACTUATOR_BASE_PATH:/actuator}
      exposure:
        include: ${ACTUATOR_EXPOSED_GATEWAY:health,info,env}

logging:
  level:
    root: ${LOG_LEVEL_APP:DEBUG}