# =====================================================
# PROFILE
# =====================================================
ACTIVE_PROFILE=dev

# =====================================================
# SERVER PORT
# =====================================================
GATEWAY_SERVICE_PORT=8080

# =====================================================
# SERVICE URLS (STATIC ROUTING)
# =====================================================
IDENTITY_SERVICE_URL=http://localhost:8081
SCHEDULE_SERVICE_URL=http://localhost:8082
CODESHARE_SERVICE_URL=http://localhost:8083

# =====================================================
# SECURITY (JWT VALIDATION ONLY)
# =====================================================
AUTH_IDENTITY_SERVICE_ISSUER_URI=http://localhost:8081

# =====================================================
# ACTUATOR
# =====================================================
ACTUATOR_BASE_PATH=/actuator
ACTUATOR_EXPOSED_DEFAULT=health,info
ACTUATOR_EXPOSED_GATEWAY=health,info,env

# =====================================================
# LOGGING
# =====================================================
LOG_LEVEL_APP=DEBUG
LOG_LEVEL_OAUTH2=INFO