# =====================================================
# PROFILE
# =====================================================
ACTIVE_PROFILE=dev

# =====================================================
# SERVER PORT
# =====================================================
AUTH_IDENTITY_SERVICE_PORT=8081

# =====================================================
# DATABASE
# =====================================================
DB_HOST=localhost
DB_PORT=5432
DB_NAME=csm
DB_USERNAME=postgres
DB_PASSWORD=postgres

DB_DRIVER=org.postgresql.Driver
DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

# =====================================================
# JPA
# =====================================================
HIBERNATE_DDL=update
SHOW_SQL=true
FORMAT_SQL=true

# =====================================================
# AUTH / SECURITY
# =====================================================
AUTH_IDENTITY_ISSUER_URI=http://localhost:8081

ACCESS_TOKEN_TTL=3600
REFRESH_TOKEN_TTL=86400

INTERNAL_S2S_CLIENT_SECRET=admin123
INTERNAL_S2S_CLIENT_ID=internal-s2s-client

OIDC_STATE_SECRET=somesecretkeyforoidcstatesomesecretkeyforoidcstate
OIDC_STATE_TTL_SECONDS=300

# =====================================================
# KEYSTORE
# =====================================================
KEYSTORE_LOCATION=classpath:auth-keystore.p12
KEYSTORE_PASSWORD=admin123
KEY_PASSWORD=admin123
KEY_ALIAS=auth-server

# =====================================================
# ACTUATOR
# =====================================================
ACTUATOR_BASE_PATH=/actuator
ACTUATOR_EXPOSED_DEFAULT=health,info

# =====================================================
# LOGGING
# =====================================================
LOG_LEVEL_APP=DEBUG
LOG_LEVEL_OAUTH2=INFO