CREATE SCHEMA IF NOT EXISTS auth_identity;

CREATE SEQUENCE IF NOT EXISTS auth_identity.auth_token_exchange_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.group_menus_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.group_roles_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.groupss_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.login_audit_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.menus_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.oidc_state_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.permissions_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.refresh_token_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.role_permissions_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.roles_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.user_devices_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.user_groups_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS auth_identity.users_seq START WITH 1 INCREMENT BY 50;

ALTER TABLE IF EXISTS auth_identity.menus
    ADD COLUMN IF NOT EXISTS navigation_type varchar(30) NOT NULL DEFAULT 'SECTION';

ALTER TABLE IF EXISTS auth_identity.menus
    ADD COLUMN IF NOT EXISTS frontend_path varchar(1000);

ALTER TABLE IF EXISTS auth_identity.menus
    ADD COLUMN IF NOT EXISTS external_url varchar(1000);

ALTER TABLE IF EXISTS auth_identity.menus
    ADD COLUMN IF NOT EXISTS permission_code varchar(150);
