spring:
  application:
    name: schedule-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_IDENTITY_SERVICE_ISSUER_URI:http://localhost:8081}

  datasource:
    driver-class-name: ${SCHEDULE_SERVICE_DB_DRIVER:${DB_DRIVER:org.postgresql.Driver}}
    url: ${SCHEDULE_SERVICE_DB_URL:${DB_URL:jdbc:postgresql://localhost:5432/csm}}
    username: ${SCHEDULE_SERVICE_DB_USERNAME:${DB_USERNAME:postgres}}
    password: ${SCHEDULE_SERVICE_DB_PASSWORD:${DB_PASSWORD:postgres}}

  jpa:
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:update}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        default_schema: schedule_live
        hbm2ddl:
          create_namespaces: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:schedule-service}
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# ----------------------------------
# KAFKA TOPICS
# ----------------------------------
schedule:
  workflow:
    approval:
      policy: ${SCHEDULE_APPROVAL_POLICY:${SCHEDULE_APPROVAL_MODE:AUTO}}
    topics:
      change-set-created: ${SCHEDULE_WORKFLOW_CHANGE_SET_CREATED_TOPIC:schedule.workflow.change-set-created}
      schedule-updated: ${SCHEDULE_WORKFLOW_SCHEDULE_UPDATED_TOPIC:schedule.workflow.schedule-updated}

# ----------------------------------
# EXTERNAL SERVICE CALLS
# ----------------------------------
services:
  identity:
    url: ${AUTH_IDENTITY_SERVICE_URL:http://localhost:8081}
    s2s:
      client-id: ${INTERNAL_S2S_CLIENT_ID:internal-s2s-client}
      client-secret: ${INTERNAL_S2S_CLIENT_SECRET:admin123}
  compare:
    url: ${SCHEDULE_COMPARE_SERVICE_URL:${SCHEDULE_PROCESSING_SERVICE_URL:http://localhost:8089}}
  processing:
    url: ${SCHEDULE_PROCESSING_SERVICE_URL:http://localhost:8085}

app:
  kafka:
    retry:
      interval-ms: ${KAFKA_RETRY_INTERVAL_MS:1000}
      max-attempts: ${KAFKA_RETRY_MAX_ATTEMPTS:3}
      dlt-suffix: ${KAFKA_DLT_SUFFIX:.DLT}

# ----------------------------------
# SERVER
# ----------------------------------
server:
  port: ${SCHEDULE_SERVICE_PORT:8087}

# ----------------------------------
# LOGGING
# ----------------------------------
logging:
  level:
    root: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.kafka: INFO
