package com.codeshare.airline.schedule.live.domain.entity;

import com.codeshare.airline.platform.core.enums.schedule.MessageType;
import com.codeshare.airline.platform.data.jpa.entity.CSMDataAbstractEntity;
import com.codeshare.airline.schedule.live.domain.enums.ScheduleChangeType;
import com.codeshare.airline.schedule.live.domain.enums.SsmOutboundStatus;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.UUID;

/**
 * Outbound SSM / ASM message dispatched to the reservation system after a
 * delta has been merged into the live schedule (SSIM Chapter 7 compliant).
 *
 * One row per individual SSM or ASM sub-message action generated by the
 * schedule-service in response to a schedule-processing-service delta.
 * The raw formatted message text (Chapter 7 wire format) is preserved for
 * resend / replay and audit purposes.
 *
 * Lifecycle:  PENDING â†’ DISPATCHED â†’ CONFIRMED | FAILED â†’ RETRYING â†’ â€¦
 */
@Entity
@Table(
        name = "live_ssm_message",
        schema = "schedule_live",
        indexes = {
                @Index(name = "idx_lssm_status",         columnList = "outbound_status"),
                @Index(name = "idx_lssm_type",           columnList = "message_type"),
                @Index(name = "idx_lssm_airline_flight",  columnList = "airline_code, flight_number"),
                @Index(name = "idx_lssm_leg",            columnList = "flight_leg_id"),
                @Index(name = "idx_lssm_version",        columnList = "schedule_version_id"),
                @Index(name = "idx_lssm_dispatched_at",  columnList = "dispatched_at"),
                @Index(name = "idx_lssm_reference",      columnList = "message_reference")
        }
)
@Getter
@Setter
@NoArgsConstructor
@SuperBuilder
public class LiveSsmMessageEntity extends CSMDataAbstractEntity {

    /* ==========================================================
       RELATIONSHIP TO THE LEG AND VERSION THAT TRIGGERED THIS
       ========================================================== */

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "flight_leg_id",
            nullable = false,
            updatable = false,
            foreignKey = @ForeignKey(name = "fk_lssm_flight_leg")
    )
    private LiveFlightLegEntity flightLeg;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "schedule_version_id",
            foreignKey = @ForeignKey(name = "fk_lssm_schedule_version")
    )
    private LiveScheduleVersionEntity scheduleVersion;

    /* ==========================================================
       SSM / ASM CHAPTER 7 â€” MESSAGE HEADER
       ========================================================== */

    @Enumerated(EnumType.STRING)
    @Column(name = "message_type", length = 10, nullable = false)
    private MessageType messageType;            // SSM or ASM

    @Column(name = "message_reference", length = 50)
    private String messageReference;            // e.g. "CSM-SSM-20250101-001"

    @Column(name = "sender", length = 10)
    private String sender;                      // originating airline designator

    @Column(name = "recipient", length = 10)
    private String recipient;                   // target system / airline designator

    @Column(name = "creation_date_raw", length = 7)
    private String creationDateRaw;             // DDMMMYY

    @Column(name = "creation_time_raw", length = 4)
    private String creationTimeRaw;             // HHMM

    /* ==========================================================
       SSM / ASM CHAPTER 7 â€” ACTION / FLIGHT DATA
       ========================================================== */

    @Enumerated(EnumType.STRING)
    @Column(name = "action_type", length = 20, nullable = false)
    private ScheduleChangeType actionType;      // NEW, TIM, EQT, CNL, RIN, REV

    @Column(name = "airline_code", length = 3, nullable = false)
    private String airlineCode;

    @Column(name = "flight_number", length = 4, nullable = false)
    private String flightNumber;

    @Column(name = "operational_suffix", length = 1)
    private String operationalSuffix;

    @Column(name = "period_start")
    private LocalDate periodStart;

    @Column(name = "period_end")
    private LocalDate periodEnd;

    @Column(name = "days_of_operation", length = 7)
    private String daysOfOperation;

    @Column(name = "departure_station", length = 3)
    private String departureStation;

    @Column(name = "arrival_station", length = 3)
    private String arrivalStation;

    @Column(name = "scheduled_departure_time")
    private LocalTime scheduledDepartureTime;

    @Column(name = "scheduled_arrival_time")
    private LocalTime scheduledArrivalTime;

    @Column(name = "aircraft_type", length = 3)
    private String aircraftType;

    /* ==========================================================
       WIRE FORMAT â€” FULL RAW CHAPTER 7 MESSAGE BODY
       ========================================================== */

    @Column(name = "raw_message_body", columnDefinition = "TEXT")
    private String rawMessageBody;

    /* ==========================================================
       DISPATCH STATE
       ========================================================== */

    @Enumerated(EnumType.STRING)
    @Column(name = "outbound_status", length = 20, nullable = false)
    private SsmOutboundStatus outboundStatus;

    @Column(name = "kafka_topic", length = 100)
    private String kafkaTopic;

    @Column(name = "kafka_partition")
    private Integer kafkaPartition;

    @Column(name = "kafka_offset")
    private Long kafkaOffset;

    @Column(name = "dispatched_at")
    private Instant dispatchedAt;

    @Column(name = "confirmed_at")
    private Instant confirmedAt;

    /* ==========================================================
       ERROR HANDLING
       ========================================================== */

    @Column(name = "retry_count")
    private Integer retryCount;

    @Column(name = "last_retry_at")
    private Instant lastRetryAt;

    @Column(name = "error_code", length = 50)
    private String errorCode;

    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    /* ==========================================================
       PROCESSING TRACEABILITY
       ========================================================== */

    @Column(name = "processing_delta_id")
    private UUID processingDeltaId;             // ID from schedule-processing-service
}
