package com.codeshare.airline.master.aircraft.serviceImpl;

import com.codeshare.airline.master.airlines.entities.Airline;
import com.codeshare.airline.platform.core.dto.master.aircraft.AircraftConfigurationDTO;
import com.codeshare.airline.master.aircraft.entities.AircraftConfiguration;
import com.codeshare.airline.master.aircraft.entities.AircraftType;
import com.codeshare.airline.master.aircraft.repository.AircraftConfigurationRepository;
import com.codeshare.airline.master.aircraft.repository.AircraftTypeRepository;
import com.codeshare.airline.master.aircraft.service.AircraftConfigurationService;
import com.codeshare.airline.master.aircraft.mappers.AircraftConfigurationMapper;
import com.codeshare.airline.master.airlines.repository.AirlineRepository;
import com.codeshare.airline.master.common.base.BaseServiceImpl;
import jakarta.persistence.EntityNotFoundException;
import org.springframework.stereotype.Service;


@Service
public class AircraftConfigurationServiceImpl
        extends BaseServiceImpl<AircraftConfiguration, AircraftConfigurationDTO, Long>
        implements AircraftConfigurationService {

    private final AircraftConfigurationRepository repository;
    private final AircraftTypeRepository aircraftTypeRepository;
    private final AirlineRepository airlineRepository;

    public AircraftConfigurationServiceImpl(
            AircraftConfigurationRepository repository,
            AircraftConfigurationMapper mapper,
            AircraftTypeRepository aircraftTypeRepository,
            AirlineRepository airlineRepository) {

        super(repository, mapper);
        this.repository = repository;
        this.aircraftTypeRepository = aircraftTypeRepository;
        this.airlineRepository = airlineRepository;
    }

    private AircraftType getAircraftType(Long id) {
        return aircraftTypeRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Aircraft type not found"));
    }

    private Airline getAirline(Long id) {
        return airlineRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Airline not found"));
    }

    @Override
    public AircraftConfigurationDTO create(AircraftConfigurationDTO dto) {

        AircraftType type = getAircraftType(dto.getAircraftTypeId());
        Airline airline = getAirline(dto.getAirlineId());

        AircraftConfiguration config = mapper.toEntity(dto);

        if (Boolean.TRUE.equals(dto.getAutoGenerated())) {

            long version =
                    repository.countByAirlineIdAndAircraftTypeId(
                            airline.getId(),
                            type.getId()
                    ) + 1;

            String generatedCode =
                    airline.getIataCode() + "-" +
                            type.getIcaoCode() + "-V" + version;

            config.setConfigurationCode(generatedCode);

        } else {

            if (dto.getConfigurationCode() == null ||
                    dto.getConfigurationCode().isBlank()) {
                throw new IllegalStateException(
                        "Configuration code must be provided when autoGenerated is false."
                );
            }

            config.setConfigurationCode(dto.getConfigurationCode());
        }

        config.setAircraftType(type);
        config.setAirline(airline);

        return mapper.toDTO(repository.save(config));
    }

    @Override
    public AircraftConfigurationDTO update(Long id, AircraftConfigurationDTO dto) {

        AircraftConfiguration existing = repository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Configuration not found"));

        AircraftType type = getAircraftType(dto.getAircraftTypeId());
        Airline airline = getAirline(dto.getAirlineId());

        mapper.updateEntityFromDto(dto, existing);

        existing.setAircraftType(type);
        existing.setAirline(airline);

        return mapper.toDTO(repository.save(existing));
    }
}