package com.codeshare.airline.data.aircraft.serviceImpl;

import com.codeshare.airline.core.dto.aircraft.AircraftConfigurationDTO;
import com.codeshare.airline.data.aircraft.eitities.AircraftConfiguration;
import com.codeshare.airline.data.aircraft.eitities.AircraftType;
import com.codeshare.airline.data.aircraft.repository.AircraftConfigurationRepository;
import com.codeshare.airline.data.aircraft.repository.AircraftTypeRepository;
import com.codeshare.airline.data.aircraft.service.AircraftConfigurationService;
import com.codeshare.airline.data.aircraft.utils.mappers.AircraftConfigurationMapper;
import com.codeshare.airline.data.core.eitities.AirlineCarrier;
import com.codeshare.airline.data.core.repository.AirlineCarrierRepository;
import com.codeshare.airline.persistence.persistence.service.BaseServiceImpl;
import jakarta.persistence.EntityNotFoundException;
import org.springframework.stereotype.Service;

import java.util.UUID;

@Service
public class AircraftConfigurationServiceImpl
        extends BaseServiceImpl<AircraftConfiguration, AircraftConfigurationDTO, UUID>
        implements AircraftConfigurationService {

    private final AircraftConfigurationRepository repository;
    private final AircraftTypeRepository aircraftTypeRepository;
    private final AirlineCarrierRepository airlineRepository;

    public AircraftConfigurationServiceImpl(
            AircraftConfigurationRepository repository,
            AircraftConfigurationMapper mapper,
            AircraftTypeRepository aircraftTypeRepository,
            AirlineCarrierRepository airlineRepository) {

        super(repository, mapper);
        this.repository = repository;
        this.aircraftTypeRepository = aircraftTypeRepository;
        this.airlineRepository = airlineRepository;
    }

    private AircraftType getAircraftType(UUID id) {
        return aircraftTypeRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Aircraft type not found"));
    }

    private AirlineCarrier getAirline(UUID id) {
        return airlineRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Airline not found"));
    }

    @Override
    public AircraftConfigurationDTO create(AircraftConfigurationDTO dto) {

        AircraftType type = getAircraftType(dto.getAircraftTypeId());
        AirlineCarrier airline = getAirline(dto.getAirlineId());

        AircraftConfiguration config = mapper.toEntity(dto);

        if (Boolean.TRUE.equals(dto.getAutoGenerated())) {

            long version =
                    repository.countByAirlineIdAndAircraftTypeId(
                            airline.getId(),
                            type.getId()
                    ) + 1;

            String generatedCode =
                    airline.getIataCode() + "-" +
                            type.getIcaoCode() + "-V" + version;

            config.setConfigurationCode(generatedCode);

        } else {

            if (dto.getConfigurationCode() == null ||
                    dto.getConfigurationCode().isBlank()) {
                throw new IllegalStateException(
                        "Configuration code must be provided when autoGenerated is false."
                );
            }

            config.setConfigurationCode(dto.getConfigurationCode());
        }

        config.setAircraftType(type);
        config.setAirline(airline);

        return mapper.toDTO(repository.save(config));
    }

    @Override
    public AircraftConfigurationDTO update(UUID id, AircraftConfigurationDTO dto) {

        AircraftConfiguration existing = repository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Configuration not found"));

        AircraftType type = getAircraftType(dto.getAircraftTypeId());
        AirlineCarrier airline = getAirline(dto.getAirlineId());

        mapper.updateEntityFromDto(dto, existing);

        existing.setAircraftType(type);
        existing.setAirline(airline);

        return mapper.toDTO(repository.save(existing));
    }
}