spring:
  application:
    name: authentication-identity-service

server:
  port: ${AUTH_IDENTITY_SERVICE_PORT:8081}

csm:
  auth:
    providers:
      azure:
        enabled: true
        priority: 1
        tenant-id: ${AZURE_TENANT_ID}
        client-id: ${AZURE_CLIENT_ID}
        client-secret-ref: env://AZURE_CLIENT_SECRET
        redirect-uri: https://auth.codeshare.io/auth/azure/callback
        scopes: "openid profile email"

      ldap:
        enabled: true
        priority: 2
        url: ldaps://ad.company.com:636
        base: dc=company,dc=com
        user-dn: CN=ldap-reader,OU=ServiceAccounts,DC=company,DC=com
        password: ${LDAP_PASSWORD}

      local:
        enabled: true
        priority: 3

security:
  jwt:
    issuer: ${AUTH_IDENTITY_ISSUER_URI}
    keystore:
      location: ${KEYSTORE_LOCATION:classpath:authentication-keystore.p12}
      store-password: ${KEYSTORE_PASSWORD}
      key-alias: ${KEY_ALIAS:authentication-server}
      key-password: ${KEY_PASSWORD}
  oidc:
    state:
      secret: ${OIDC_STATE_SECRET:changeit}
      ttl-seconds: ${OIDC_STATE_TTL_SECONDS:300}

logging:
  level:
    org.springframework.security: INFO
    com.codeshare.airline: INFO