spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_IDENTITY_ISSUER_URI}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://${AUTH_IDENTITY_SERVICE_NAME:auth-identity-service}
          predicates:
            - Path=/api/auth/**, /api/menus/**
          filters:
            - TokenRelay

        - id: tenant-service
          uri: lb://${TENANT_SERVICE_NAME:tenant-service}
          predicates:
            - Path=/api/tenant/**
          filters:
            - TokenRelay

        - id: ingestion-service
          uri: lb://${SSIM_INGESTION_SERVICE_NAME:schedule-ingestion-service}
          predicates:
            - Path=/api/ingestion/**
          filters:
            - TokenRelay


server:
  port: ${GATEWAY_SERVICE_PORT:8080}


management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSED_GATEWAY:health,info,env}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: INFO


gateway:
  security:
    auth:
      public-paths:
        - /api/auth/login
        - /api/auth/refresh
        - /api/auth/logout
        - /api/auth/oidc/**
        - /.well-known/**
    api:
      public-paths:
        - /actuator/**
        - /swagger-ui/**
        - /v3/api-docs/**
        - /v3/api-docs.yaml
        - /health
        - /info
