spring:
  application:
    name: registry-service

server:
  port: ${REGISTRY_SERVICE_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0

  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info
