spring:
  application:
    name: tenant-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_IDENTITY_ISSUER_URI:http://localhost:8081}

      client:
        registration:
          internal:
            provider: authentication-provider
            client-id: ${INTERNAL_S2S_CLIENT_ID}
            client-secret: ${INTERNAL_S2S_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - internal.read
              - internal.write
              - internal.command
            client-authentication-method: client_secret_basic
        provider:
          auth-provider:
            token-uri: ${AUTH_IDENTITY_ISSUER_URI:http://localhost:8081}/oauth2/token

server:
  port: ${TENANT_SERVICE_PORT:8082}

security:
  internal:
    oauth2:
      registration-id: internal
      principal: ${spring.application.name}
