spring:
  application:
    name: schedule-ingestion-service

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_IDENTITY_SERVICE_ISSUER_URI:http://localhost:8081}

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/csm}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:update}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        default_schema: schedule_ingestion

  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}
    packages:
      trust-all: true

server:
  port: ${SCHEDULE_INGESTION_SERVICE_PORT:8082}

logging:
  level:
    org.springframework.web: DEBUG
    org.apache.camel.component.file: DEBUG

# ----------------------------------
# INGESTION CONFIG
# ----------------------------------
ingestion:
  local-root: ${INGESTION_LOCAL_ROOT:C:/Users/mdwas/Projects/messages}

  allowed-extensions:
    SSIM: [txt, ssim]
    SSM: [txt, ssim]
    ASM: [txt, ssim]

# ----------------------------------
# CAMEL CONFIG
# ----------------------------------
camel:
  springboot:
    auto-startup: false

# ----------------------------------
# APP CONFIG
# ----------------------------------
app:
  crypto:
    secret: ${APP_CRYPTO_SECRET:YOUR_16_32_BYTE_SECRET_KEY}