ACTIVE_PROFILE=dev

SCHEDULE_INGESTION_SERVICE_PORT=8082

DB_HOST=localhost
DB_PORT=5432
DB_NAME=csm
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DRIVER=org.postgresql.Driver
DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

SHOW_SQL=false
FORMAT_SQL=true
HIBERNATE_DDL=update

ACTIVEMQ_BROKER_URL=tcp://localhost:61616
ACTIVEMQ_USER=admin
ACTIVEMQ_PASSWORD=admin

INGESTION_LOCAL_ROOT=C:/Users/mdwas/Projects/messages

APP_CRYPTO_SECRET=YOUR_16_32_BYTE_SECRET_KEY

# =====================================================
# SECURITY (JWT VALIDATION ONLY)
# =====================================================
APP_SECURITY_ENABLED=false
AUTH_IDENTITY_SERVICE_ISSUER_URI=http://localhost:8081
